 * Serving Flask app 'app'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://10.0.3.164:5002
[33mPress CTRL+C to quit[0m
[2025-10-23 10:14:02,755] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/app.py", line 59, in index
    return render_template('index.html', menu_items=menu_items, src_available=src_available)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/workspaces/Kitty-Tools/webapp/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/workspaces/Kitty-Tools/webapp/templates/base.html", line 37, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/templates/index.html", line 11, in block 'content'
    <a class="btn" href="{{ url_for(item.id) }}">Abrir</a>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/app.py", line 2034, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/flask/app.py", line 2023, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kitty-Tools/webapp/.venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'exit'. Did you mean 'index' instead?
127.0.0.1 - - [23/Oct/2025 10:14:02] "[35m[1mGET / HTTP/1.1[0m" 500 -
127.0.0.1 - - [23/Oct/2025 10:14:02] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
